### ISSUE TITLE
Forward/backward navigation in a sub-tree

### ISSUE THREAD

**Issue by ransagy** [bjorkstromm/depends#20]
I think it would be very useful to be able to navigate up and down the trees. For example, If im looking at Package A, Being able to "select" something from the Depends or Reverse Depends lists and switch to that (and be able to go "back") can be very useful to quickly understand how a certain package is used.

**Comment by bjorkstromm** [comment]
@ransagy sorry for the late reply. I think that's a great idea. Select should IMO be done by pressing <space> or similar.

**Comment by bjorkstromm** [comment]
Fixed by #25
